///*
// * This source file was generated by the Gradle 'init' task
// */
//package bitcamp.project1.DongIn;
//
//import bitcamp.project1.util.Prompt;
//import bitcamp.project1.vo.MoneyFlow;
//import java.util.ArrayList;
//import java.util.Date;
//import java.util.LinkedList;
//import java.util.List;
//
//public class App {
//
//    public static String[] menus = {"작성", "조회", "수정", "삭제", "종료"};
//
//    public static void main(String[] args) {
//
//    }
//
//

//
//
//    public static void executeCreate() {
//    }
//
//    public static int inputAmount(String message, Object... args) {
//        while (true) {
//            try {
//                int amount = Prompt.inputInt(message);
//                return amount;
//            } catch (NumberFormatException e) {
//                System.out.println("올바른 금액을 입력하세요.");
//            }
//        }
//    }
//
//    public static String inputIncomeOrSpend(String message, Object... args) {
//        while (true) {
//            try {
//                System.out.println("1.   수입");
//                System.out.println("2.   지출");
//
//                int incomeOrSpend = Prompt.inputInt(message);
//
//                switch (incomeOrSpend) {
//                    case 1:
//                        return "수입";
//                    case 2:
//                        return "지출";
//                    default:
//                        System.out.println("올바른 항목을 선택해주세요.");
//                }
//            } catch (NumberFormatException e) {
//                System.out.println("숫자로 입력해주세요.");
//            }
//        }
//    }
//
//    public static String inputCategory(String incomeOrSpend, String message, Object... args) {
//        while (true) {
//            try {
//                if (incomeOrSpend.equals("수입")) {
//                    for (int i = 0; i < DepositCategory.values().length; i++) {
//                        System.out.println(i + 1 + ". " + DepositCategory.values()[i].getName());
//                    }
//
//                    int inputCategory = Prompt.inputInt(message);
//
//                    if (0 < inputCategory && inputCategory < DepositCategory.values().length + 1) {
//                        return DepositCategory.values()[inputCategory - 1].getName();
//                    } else {
//                        System.out.println("올바른 항목을 선택하세요. ");
//                    }
//                } else if (incomeOrSpend.equals("지출")) {
//                    for (int i = 0; i < WithdrawCategory.values().length; i++) {
//                        System.out.println(i + 1 + ". " + WithdrawCategory.values()[i].getName());
//                    }
//
//                    int inputCategory = Prompt.inputInt(message);
//
//                    if (0 < inputCategory && inputCategory < WithdrawCategory.values().length + 1) {
//                        return WithdrawCategory.values()[inputCategory - 1].getName();
//                    } else {
//                        System.out.println("올바른 항목을 선택하세요. ");
//                    }
//                } else {
//                    return null;
//                }
//            } catch (NumberFormatException e) {
//                System.out.println("숫자로 입력해주세요.");
//            }
//        }
//    }
//
//    public static String inputNote(String message, Object... args) {
//        return Prompt.input(message);
//    }
//
//    public static String inputPaymentMethod(String message, Object... args) {
//        while (true) {
//            try {
//                for (int i = 0; i < PaymentMethod.values().length; i++) {
//                    System.out.println(i + 1 + ". " + PaymentMethod.values()[i].getName());
//                }
//                int inputPaymentMethod = Prompt.inputInt(message);
//
//                if (0 < inputPaymentMethod
//                    && inputPaymentMethod < PaymentMethod.values().length + 1) {
//                    return PaymentMethod.values()[inputPaymentMethod - 1].getName();
//                } else {
//                    System.out.println("올바른 항목을 선택하세요. ");
//                }
//            } catch (NumberFormatException e) {
//                System.out.println("숫자로 입력해주세요.");
//            }
//        }
//    }
//
//
//}
//
